### ISSUE TITLE
eval bug

### ISSUE THREAD

**Issue by KaiGuo20** [Graph-COM/SubgraphRAG#13]
Hi,
Can you help me to solve this bug?  When I use "python eval.py -d webqsp -p P" 

  File "/workspace/SubgraphRAG/retrieve/eval.py", line 7, in main
    gpt_triple_dict = torch.load(f'data_files/{args.dataset}/gpt_triples.pth')
  File "/anaconda3/envs/retriever/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/anaconda3/envs/retriever/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/anaconda3/envs/retriever/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data_files/webqsp/gpt_triples.pth'

**Comment by mufeili** [comment]
Thank you for your interest in our work and reporting this bug. This should have been fixed with #14 . I've closed the issue for now. Feel free to reopen it if the issue still exists.

**Comment by KaiGuo20** [comment]
Sorry, there is a another bug: 
Traceback (most recent call last):
  File "/workspace/SubgraphRAG/retrieve/eval.py", line 76, in <module>
    main(args)
  File "/eworkspace/SubgraphRAG/retrieve/eval.py", line 7, in main
    gpt_triple_dict = torch.load(f'data_files/{args.dataset}/gpt_triples.pth')
  File "/anaconda3/envs/retriever/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/anaconda3/envs/retriever/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by mufeili** [comment]
Could you share your python/PyTorch versions?

**Comment by KaiGuo20** [comment]
> Could you share your python/PyTorch versions? The error message suggests potential pickle protocol compatibility issues.

2.1.0+cu121

**Comment by mufeili** [comment]
How about python version?

**Comment by KaiGuo20** [comment]
> How about python version?

Python 3.10.15

**Comment by mufeili** [comment]
Could you try directly going to say the `data_files/webqsp` directory, and loading the file with

```bash
import torch
data = torch.load('gpt_triples.pth')
```

If this does not work, try downloading only these files again.

**Comment by KaiGuo20** [comment]
> downloading only these files again

Downloading these files again works. Thanks.

**Comment by mufeili** [comment]
Glad to know that! I'll close the issue.
